inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
Layout/HashAlignment:
  Exclude:
    - '*.gemspec'
Gemspec/AddRuntimeDependency:
  Enabled: false # https://github.com/rubocop/rubocop/pull/13030#discussion_r1674791776
